export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CHANGE_INPUT_LOGIN_EMAIL = "CHANGE_INPUT_LOGIN_EMAIL";
export const CHANGE_INPUT_LOGIN_PASSWORD = "CHANGE_INPUT_LOGIN_PASSWORD";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SETUP_PENDING = "SETUP_PENDING";
export const SETUP_SUCCESS = "SETUP_SUCCESS";
export const SETUP_FAILURE = "SETUP_FAILURE";

//appActions, appReducer
export const GET_TEAMS_PENDING = "GET_TEAMS_PENDING";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const GET_TEAMS_FAILURE = "GET_TEAMS_FAILURE";
export const CLEAR_TEAMS = "CLEAR_TEAMS";
export const GET_CATEGORIES_PENDING= "GET_CATEGORIES_PENDING";
export const GET_CATEGORIES_SUCCESS= "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE= "GET_CATEGORIES_FAILURE";
export const SET_TEAM_NAME= "SET_TEAM_NAME";
export const CLEAR_TEAM_NAME= "CLEAR_TEAM_NAME";
