//authActions, authReducer
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SETUP_PENDING = "SETUP_PENDING";
export const SETUP_SUCCESS = "SETUP_SUCCESS";
export const SETUP_FAILURE = "SETUP_FAILURE";
export const CHANGE_INPUT_LOGIN = "CHANGE_INPUT_LOGIN";
export const CHANGE_INPUT_REGISTER = "CHANGE_INPUT_REGISTER";

//appActions, appReducer
export const GET_TEAMS_PENDING = "GET_TEAMS_PENDING";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
export const GET_TEAMS_FAILURE = "GET_TEAMS_FAILURE";
export const CLEAR_TEAMS = "CLEAR_TEAMS";
export const GET_CATEGORIES_PENDING= "GET_CATEGORIES_PENDING";
export const GET_CATEGORIES_SUCCESS= "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE= "GET_CATEGORIES_FAILURE";
export const SET_CATEGORY_ID= "SET_CATEGORY_ID";
export const SET_TEAM_NAME= "SET_TEAM_NAME";
export const SET_TEAM_ID= "SET_TEAM_ID";
export const CLEAR_TEAM_NAME= "CLEAR_TEAM_NAME";
export const GET_BOOKMARKS_PENDING = "GET_BOOKMARKS_PENDING";
export const GET_BOOKMARKS_SUCCESS = "GET_BOOKMARKS_SUCCESS";
export const GET_BOOKMARKS_FAILURE = "GET_BOOKMARKS_FAILURE";
export const CLEAR_BOOKMARKS = "CLEAR_BOOKMARKS";
export const CLEAR_CATEGORIES = "CLEAR_CATEGORIES";
export const CHANGE_INPUT_APP = "CHANGE_INPUT_APP";

export const POST_NEWTEAM_PENDING = "POST_NEWTEAM_PENDING";
export const POST_NEWTEAM_SUCCESS = "POST_NEWTEAM_SUCCESS";
export const POST_NEWTEAM_FAILURE = "POST_NEWTEAM_FAILURE";
export const POST_NEWCATEGORY_PENDING = "POST_NEWCATEGORY_PENDING";
export const POST_NEWCATEGORY_SUCCESS = "POST_NEWCATEGORY_SUCCESS";
export const POST_NEWCATEGORY_FAILURE = "POST_NEWCATEGORY_FAILURE";

export const POST_NEWBOOKMARK_PENDING = "POST_NEWBOOKMARK_PENDING";
export const POST_NEWBOOKMARK_SUCCESS = "POST_NEWBOOKMARK_SUCCESS";
export const POST_NEWBOOKMARK_FAILURE = "POST_NEWBOOKMARK_FAILURE";
export const CHANGE_INPUT_NEW_BOOKMARK = "CHANGE_INPUT_NEW_BOOKMARK";
export const CLEAR_CATEGORY_ID = "CLEAR_CATEGORY_ID";
export const CATEGORY_CLICKED = "CATEGORY_CLICKED";
export const CLEAR_CATEGORY_CLICKED = "CLEAR_CATEGORY_CLICKED";
export const SET_CATEGORY_NAME = "SET_CATEGORY_NAME";
export const CLEAR_CATEGORY_NAME = "CLEAR_CATEGORY_NAME";
export const CHANGE_INPUT_EDIT_BOOKMARK = "CHANGE_INPUT_EDIT_BOOKMARK";
export const PUT_BOOKMARK_PENDING = "PUT_BOOKMARK_PENDING";
export const PUT_BOOKMARK_SUCCESS = "PUT_BOOKMARK_SUCCESS";
export const PUT_BOOKMARK_FAILURE = "PUT_BOOKMARK_FAILURE";
export const SET_EDIT_BOOKMARK = "SET_EDIT_BOOKMARK";
export const EMPTY_ERRORS = "EMPTY_ERRORS";


//todo : GET_TEAM_CONTENT + CLEAR_TEAM_CONTENT mettre le get dans la page mon-compte? et le clear dans le composant Team?


